grammar:
    rules_range: [1, 5]
    nonterminals_range: [1, 3]
    only_non_empty_nonterminals: False
    unreachable_nonterminals: False
    only_generating_nonterminals: False

    production_separator: "|"
    arrow: "->"
    rule_separator: ";\n"

production:
    max_symbols: 5

terminals:
    regex: "[a-z0-9]"

nonterminals:
    nonterminal_start: "["
    nonterminal_end: "]"
    regex: "[A-Z]"