grammar:
    nonterminals_range: [1, 6]
    rules_for_nonterminal_range: [1, 3]
    only_non_empty_nonterminals: False
    unreachable_nonterminals: False
    only_generating_nonterminals: False

    start_nonterminal: "S"
    epsilon: "eps"

    production_separator: "|"
    arrow: "->"
    rule_separator: ";"

production:
    max_symbols: 5

terminals:
    regex: "[a-z0-9]"
    max_length: 4

nonterminals:
    nonterminal_start: "["
    nonterminal_end: "]"
    regex: "[A-Z]"
    max_length: 4